### PR TITLE
Feature: Add `emit` option

### LINKED ISSUE #84: OOM with the big stats object
We have a project that the stats object may be larger than 10GB, so using `JSON.stringify()` is not feasible. Is it possible to use https://github.com/Faleij/json-stream-stringify instead of the current approach?

### PR DESCRIPTION
**Pull request by ryan-roemer**
- Adds `emit` option
- Provide test examples, including example to handle custom stream pipe writing. Fixes #84 

@khanguy00 -- mind checking out this branch and the test example with streaming and see if it meets your requirements?

### CODE REVIEW

**Comment by khanguy00** [comment]
Just checked, looks good.

But I think this approach is just to move all code of stream processing out of the stats plugin. So I think I probably implement the stats plugin by my own now, so I don't put too many custom logic in our `webpack.conf` file.

**Comment by ryan-roemer** [comment]
Sure. Whatever works for you. As the plugin author, we generally don’t want file writing logic inside webpack land in a plugin because it’s very hard to generalize given all the things that that can happen on webpack output, and want it left up to the ultimate developer. 

Here, we at least still have a path for developers to integrate as they see fit when they can guarantee how they write to disk will actually work

**Comment by khanguy00** [comment]
Right. That makes sense. Thanks anyway.

**Comment by ryan-roemer** [comment]
Released in `webpack-stats-plugin@1.1.0`

**Pull request merged**
