### PR TITLE
Bug: use rawsource in webpack5+

### LINKED ISSUE #65: use webpack sources instead pseudo object
Ref: https://github.com/webpack-contrib/compression-webpack-plugin/issues/236

It is wrong to do this https://github.com/FormidableLabs/webpack-stats-plugin/blob/main/lib/stats-writer-plugin.js#L140 (maybe time to typescript or typescript jsdoc to avoid these problems in future).

It should be for webpack@5:
```js
const source = curCompiler.webpack 
  // webpack@5
  ? curCompiler.webpack.sources.RawSource(statsBuf) 
  // webpack@4
  : {
    source() {
      return statsBuf;
    },
    size() {
      return statsBuf.length;
    }
  }
```

### PR DESCRIPTION
**Pull request by ryan-roemer**
Fixes #65 

cc @alexander-akait

### CODE REVIEW

**Review by alexander-akait — APPROVED** [review]
Looks good, do we have tests for webpack@5?

**Comment by ryan-roemer** [comment]
@alexander-akait Yep. we test all of webpack1-5 😄  https://github.com/FormidableLabs/webpack-stats-plugin/tree/main/test

**Comment by alexander-akait** [comment]
oh :smile: maybe time to drop very old versions (1,2,3) :smile: Anyway feel free to merge

**Comment by ryan-roemer** [comment]
Released in `webpack-stats-plugin@1.0.3`

**Pull request merged**
