### PR TITLE
Add support for Webpack 4's plugin API

### PR DESCRIPTION
**Pull request by jdelStrother**
WDYT?  The diff on github looks like I rewrote everything, but it's mostly just whitespace changes from extracting emitStats to a separate function.   https://github.com/FormidableLabs/webpack-stats-plugin/compare/master...jdelStrother:patch-1?w=1 might be clearer.

### CODE REVIEW

**Comment by ryan-roemer** [comment]
Looks great! Thanks!

**Comment by jdelStrother** [comment]
Ugh, I've just spotted that I accidentally added yarn.lock - sorry about that.   Do you want a PR to remove it?

**Comment by ryan-roemer** [comment]
@jdelStrother -- No worries. I'm switching the dev build to yarn, dropping old nodes, dropping gulp and doing a whole bunch of modernizing the build :)

**Comment by ryan-roemer** [comment]
Released in `webpack-stats-plugin@0.2.0`

@jdelStrother -- I moderized the code to node4+ and everything _should_ work, but mind reporting back that your new webpack4 changes work as expected with the npm-published version? Thanks!

**Comment by jdelStrother** [comment]
Yup, looks good thanks!

**Pull request merged**
